name: "Setup Environment"
description: "Common setup"
inputs:
  key:
    description: "Shared Key"
    required: false
    default: global-rust-cache
  dir:
    description: "Working directory"
    required: false
    default: ./
runs:
  using: "composite"
  steps:
    - name: Rust cache
      uses: swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      with:
        shared-key: ${{ inputs.key }}
    - name: Mise
      uses: jdx/mise-action@9dc7d5dd454262207dea3ab5a06a3df6afc8ff26 # v3.4.1
      with:
        working_directory: ${{ inputs.dir }}
    - name: Ensure cargo fmt is installed
      shell: bash
      run: rustup component add rustfmt
    - name: Ensure cargo clippy is installed
      shell: bash
      run: rustup component add clippy
    - name: Double check Rust is installed
      shell: bash
      run: mise install rust && rustc --version && rustfmt --version
